### ISSUE TITLE
Error: Failed with error: Eof during processing file

### ISSUE THREAD

**Issue by joshtynjala** [HaxeFoundation/haxelib#589] opened 2023-02-21 20:40 UTC
I tried three times, but I kept getting the same error.

```
Sending data.... 
File #40700878 accepted : 122365071 bytes written
Processing file.... 
Error: Failed with error: Eof
```

See also this Haxe Community thread started by someone else who gets the same error (I replied too):

https://community.haxe.org/t/trying-to-publish-to-haxelib-using-ci-cd/3865

**Comment by andyli** [comment] 2023-02-21 22:44
Thank for the report. I can reproduce with a slightly large zip as suggested. Looking into it now.

**Comment by andyli** [comment] 2023-02-22 00:35
The problem is Cloudflare's R2 not accepting our multipart upload, which is used for files larger than a few MB.

haxelib server uploads files through our internal minio gateway or using aws-sdk-neko, but R2 is not happy with any of them.

I guess I will have to find a tool that can do the upload properly (rclone? s3cmd?), and then update the server to use it.

I'm too tired right now, will continue tmr.

**Comment by andyli** [comment] 2023-02-22 13:51
Fixed by using rclone for file upload.

**Closed by andyli** 2023-02-22 13:51 UTC
