### ISSUE TITLE
Installing lime installs unknown[1.0.0] lib

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/haxelib#213] opened 2015-05-23 08:47 UTC
`haxelib install lime`

downloaded lime
and said
`current version is 1.0.0` - but downloaded version is 2.2.0
And new lib appeared in `haxelib list` - `unknown[1.0.0]`
When I run my project I got - `lime is not installed`

I tried again to install lime `haxelib install lime`, same got issue (lime is not presented in `haxelib list`)

removing `unknown` lib by `haxelib remove unknown`, then installing lime again worked.

It's hard to reproduce it, sorry I don't have much info about it, maybe I had running FD when I did that.

**Comment by ibilon** [comment] 2015-05-23 09:12
Probably a duplicate of https://github.com/HaxeFoundation/haxelib/issues/187
though it's weird it worked for you the second time.

**Comment by Simn** [comment] 2015-06-18 22:13
duplicate

**Closed by Simn** 2015-06-18 22:13 UTC
