### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxelib#337] opened 2016-07-17 11:58 UTC
When trying to upload a new release I am getting

```
> haxelib submit target/haxelib-upload.zip
Password :
Sending data....
File #59855853 accepted : 26050 bytes written
Processing file....
Error: failed to upload /var/www/html/files/3.0/haxe-doctest-1,0,1.zip to s3://lib.haxe.org/files/3.0/haxe-doctest-1,0,1.zip
```

**Comment by nadako** [comment] 2016-07-17 12:17
uh oh. @andyli

**Comment by andyli** [comment] 2016-07-17 12:30
ummm... I'm looking into it.
When did you submit the release, @sebthom?
Somehow I cannot find the relevant log in the system...

**Comment by sebthom** [comment] 2016-07-17 12:34
I am trying it like now.

**Comment by andyli** [comment] 2016-07-17 12:39
Ok, I've just reproduced it. And I've restarted the server, which seems to solve the problem for now.
I will keep this open until I find the root cause of it since I think there is indeed some wrong.

**Comment by jgranick** [comment] 2016-07-18 22:37
I'm having trouble as well

```bash
> haxelib submit lime-3.0.1.zip
Password : 
Sending data....
Custom(std@socket_send)
```

I tried from two systems, Ubuntu 64-bit and Windows 10, running a dev build of Haxe 3.3.0 and Haxe 3.2.1, respectively. Thanks :smile:

**Comment by back2dos** [comment] 2016-07-19 06:42
With lime size might be the trouble. If there was a server change (was
there?) then you need to make sure the server accepts uploads > 100MB.

**Comment by andyli** [comment] 2016-07-19 09:15
I've reproduced the issue, and it was fixed in f5323c90635ee6ed023c4006109e12e1d789df81.
@jgranick Please retry.

**Comment by TheoSabattie** [comment] 2016-07-20 00:17
Hi andyli, 

I have the same issue : 
```
Package : .
Password :
Sending data....
File #1686501 accepted : 20574 bytes written
Processing file....
failed to upload /var/www/html/files/3.0/exceljs-hx-0,8,0.zip to s3://lib.haxe.o
rg/files/3.0/exceljs-hx-0,8,0.zip
```

And I found this page when I search "excel" on haxelib website:
![Website issue](http://puu.sh/q7xDV/64bbe16994.png)

**Comment by andyli** [comment] 2016-07-20 08:03
@TheoSabattie I've just restarted the server, please try again!

Basically the problem is a memory leak, that keeps the memory utilization going up. Once the EC2 instance is out of memory, some operation like `haxelib submit` will fail. I'm still tracking down the memory leak. In the mean time, I will restart the server (takes a few seconds) often to keep it in a working state.

**Comment by ciscoheat** [comment] 2016-07-20 11:13
Thanks for the info! I have the same problem as well now.

**Comment by ciscoheat** [comment] 2016-07-20 11:14
Additional errors:

```
Sending data....
File #62672001 accepted : 39449 bytes written
Processing file....
Error: Invalid file id #62672001
```

**Comment by andyli** [comment] 2016-07-20 11:47
ummm... That's a new error, possibly not related to the memory leak. I will look into it.

**Comment by TheoSabattie** [comment] 2016-07-20 16:49
It's ok for me. 

Thanks a lot @andyli :)

**Comment by ciscoheat** [comment] 2016-07-21 21:10
I tried again a couple of times, and eventually it worked for me as well.

**Comment by andyli** [comment] 2016-07-22 20:46
The `Error: Invalid file id` is fixed and should never happen again (i.e. please report if it happens).

**The cause**

We have to make 2 requests during a `haxelib submit`:
 1. The client upload the zip file to the server and the server saves it as a tmp file.
 2. The client asks the server to actually process the zip file.

Since we've config AWS to use auto-scaling, at some point there could be 2 instances running in the cloud, and the load balancer will route traffics to different instances.

The error happens when the 2 requests are sent to different instances. It is because the tmp file is located at an instance that the actual processing instance has no access.

**The fix**

We've now sync the tmp file in step 1 to S3. In step 2, when the file is not found locally, it will fetch it from S3. When the process finish, the tmp file will be deleted (locally as well as in S3).

**Comment by ibilon** [comment] 2016-07-23 09:55
Hey @andyli I'm curious, how does the first instance (if there's two) know to delete the temp file?

**Comment by andyli** [comment] 2016-07-23 09:59
The first instance will not delete the local tmp file. Disk space is not yet a problem right now. Later we can try to periodically delete the tmp files based on file creation time.

**Comment by kevinresol** [comment] 2016-07-25 01:38
Does as support session affinity, i.e. request from the same client will always go to the same instance.

**Comment by andyli** [comment] 2016-07-25 01:43
Yes, I've turned that on also. But I'm not sure if it will work for us because I don't think our neko Http class support cookies...

**Comment by saumya** [comment] 2016-07-31 08:04
Opps! First time here. Trying to submit a haxelib, a new one and came across the problem.

**Comment by andyli** [comment] 2016-08-02 14:58
I've restarted the but forgot to reply here. Please try again, @saumya.

This issue is quite hard to track down the root cause. I can reproduce the upload issue locally inside a docker container, but not when using the local Apache directly. Maybe it is related to the GC not functioning nicely in an environment with less memory (1GB for my docker container, same as our AWS free tier). Or, maybe there is a problem on creating processes because I can see that the error could occur when there is still 200-300 MB memory left. However, it doesn't seem to be the famous docker zombie process issue, since `ps faux` didn't show any suspicious process.

For now, I try to avoid creating new processes by using the aws c++ sdk instead of calling the aws cli for uploading files to S3. We will see if it helps or not.

I have to say I'm quite frustrated with this bug.

**Comment by saumya** [comment] 2016-08-03 17:04
Thanks @andyli my first haxelib is got submitted and in the list now.

**Comment by andyli** [comment] 2016-08-18 19:50
Haven't done any manually restart for 2 week. Let's call this fixed for now.

**Closed by andyli** 2016-08-18 19:50 UTC
Labels: bug
