### ISSUE TITLE
Error "Lib doesn't have a run script" should be thrown for dev-version.

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxelib#274] opened 2016-01-06 16:29 UTC
Error about "Library does not have a run script" doesn't throw when version is `dev`.

```bash
~ > haxelib list flixel
flixel: [3.3.12]
~ > haxelib run flixel
Library flixel version 3.3.12 does not have a run script
~ > haxelib list heaps
heaps: git [dev:/Users/ak/Developer/Haxe/libs/heaps/git]
~ > haxelib run heaps
~ > # nothing
```

_I'm not sure, is this planned behaviour?_

**Comment by ibilon** [comment] 2016-03-10 15:00
Doesn't happen anymore, and the code for run doesn't seem to ignore missing run.n for dev version.

**Comment by nadako** [comment] 2016-03-10 15:13
Well, this exact case reproduces, but that's because `heaps` actually HAS a `run.n` file. If I delete it, it complains, so I'm closing this issue.

**Closed by nadako** 2016-03-10 15:13 UTC
