### ISSUE TITLE
lib.haxe.org: markdown tables don't work

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#299] opened 2016-03-13 09:21 UTC
See the readme of http://lib.haxe.org/p/flixel/:

![](http://i.imgur.com/q19II99.png)

On GitHub it looks like this:

![](http://i.imgur.com/Eyghilk.png)

**Comment by nadako** [comment] 2016-03-13 10:10
Hmm, I thought tables were added to haxe markdown library. I'll check it.

**Comment by nadako** [comment] 2016-03-13 10:26
Actually, this is a duplicate of #254

**Comment by nadako** [comment] 2016-03-13 10:27
I'll try to look into fixing it in markdown, but I'd still just use pandoc or something like I said in #254

**Comment by ibilon** [comment] 2016-03-13 10:30
I'd go for pandoc, just because it's not in haxe doesn't mean we shouldn't use it,
we didn't rewrite apache and mysql :p
If it's the better tool for the job then why hesitate.

**Comment by nadako** [comment] 2016-03-13 10:31
BTW, I ported commonmark.js to haxe https://github.com/nadako/commonmark-hx, but I only managed it to pass tests on js and c# targets :-P

**Comment by nadako** [comment] 2016-03-13 10:32
I'll try integrating pandoc, let's see if it's easy or not

**Comment by nadako** [comment] 2016-03-13 10:36
Oh, it's probably requires `pandoc` binary to be installed on our servers (or somehow copied by `ufront deploy`).

**Comment by Simn** [comment] 2016-03-13 10:38
I don't have anything against pandoc but I think it's really unfortunate if Haxe doesn't have a proper markdown library. We should look into getting this right, I don't think it's that complicated.

**Comment by ibilon** [comment] 2016-03-13 10:42
@nadako tried inserting your code from #254 in https://github.com/HaxeFoundation/haxelib/blob/development/src/website/controller/ProjectController.hx#L47 and it worked perfectly
(the css for table makes them 100% in width, which is weird, although not an issue with pandoc/haxe-markdown)

**Comment by nadako** [comment] 2016-03-13 10:43
Yeah I guess it works for real-world cases, but the CommonMark test suit just hangs up neko :)

**Comment by nadako** [comment] 2016-03-13 10:44
oh wait, you're talking about pandoc.

**Comment by ibilon** [comment] 2016-03-13 10:51
Yeah.

We could use a process to a cs version of commonmark-hx if neko doesn't work yet, instead of pandoc.

**Comment by nadako** [comment] 2016-03-13 11:04
I don't know. I don't feel like it's ready to use in production, apparently c# version is much slower than js one too: https://travis-ci.org/nadako/commonmark-hx

I'll try to fix this particular issue in haxe-markdown for now.

**Comment by nadako** [comment] 2016-03-13 11:47
Apparently, commonmark spec doesn't define tables, so there's no implementation for that neither in commonmark.js, nor commonmark-hx, so yeah, we should fix haxe-markdown.

Does anyone know tho, why is colons (`:`) are handled here? https://github.com/dpeek/haxe-markdown/commit/9c6a25db7ba9ac9df4d24cfbd94b9d89cf50b965#diff-94a768d35a21dae7c044af3a8e3d594aR143 Github spec doesn't say anything about colons in table separators.

**Comment by Simn** [comment] 2016-03-13 11:51
Maybe @dpeek remembers!

**Comment by nadako** [comment] 2016-03-13 12:05
Oh, apparently these are aligning hints, but Github markdown doesn't support it, so I wonder where does it come from.

**Comment by nadako** [comment] 2016-03-13 12:35
Okay, I _think_ I fixed it in https://github.com/dpeek/haxe-markdown/pull/26. I don't know how long it'll take to be reviewed/merged though...

**Comment by nadako** [comment] 2016-03-13 12:51
I found where alignment stuff comes from! It's indeed supported by GFM: https://help.github.com/articles/organizing-information-with-tables/

But they are bound to hyphens, not pipes. Also GFM requires at lest 3 hyphens, while haxe-markdown doesn't care about it. Oh well...

aaaaaaaaaaaaaaa|bbbbbbbbbbbbbbbbbb|cccccccccccccccccc
  :--- | :---: | ---:
1|2|3

**Comment by nadako** [comment] 2016-03-13 18:59
I guess I'll try pointing our build configs to my fixed markdown repo and see what happens.

**Comment by nadako** [comment] 2016-03-13 19:08
Actually, there's an easy way for a temporary fix :-P

**Comment by nadako** [comment] 2016-03-13 19:21
Deployed a temp fix.

**Comment by Gama11** [comment] 2016-03-17 15:16
Should this be closed then? Or do you want to keep it open beacuse it's just a "temp fix"?

**Comment by nadako** [comment] 2016-03-17 15:21
I'm not sure. @dpeek accepted my PR to haxe-markdown, but I think what I done doesn't strictly follow GFM table spec, so I think I need to look into this, then prepare a new PR, then wait for haxe-markdown haxelib release, remove this hack and change required markdown version in the hxmls. Then this should be closed :)

**Comment by markknol** [comment] 2018-06-18 21:09
I'm closing this because its a markdown lib related issue.

**Closed by markknol** 2018-06-18 21:09 UTC
Labels: bug, website
