### ISSUE TITLE
When installing default libs (eg. hxcpp) check that lib isn't already specified

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxelib#511] opened 2021-04-17 19:43 UTC
I need to use a specific version of hxcpp, so I add `--library hxcpp:git:https://github.com/haxiomic/hxcpp#patch-3` to the hxml

when users run `haxelib install build.hxml`. The result is both hxcpp 4.2.1 and git are installed but 4.2.1 takes priority:

```
Loading info about the required libraries
Haxelib is going to install these libraries:
  hxcpp
  haxe-c-bridge - 0.5.3
  hxcpp - 4.2.1
Continue? [y/n/a] ? y
```

**Comment by haxiomic** [comment] 2021-04-19 16:11
Hope to PR a fix myself, not a major change

**Comment by Simn** [comment] 2021-11-04 08:59
I got a request from a Haxe Foundation partner to prioritize this issue. So, any chance for that PR? :)

**Comment by haxiomic** [comment] 2021-11-04 10:16
It’s crunch time this week for me on contract work :(:(, I can get to this but after Nov 19th

**Comment by RealyUniqueName** [comment] 2021-11-05 13:46
I've pushed a fix, but it needs a test to close the issue.

**Comment by tobil4sk** [comment] 2021-11-13 00:03
I've looked into this a bit, and it seems to be completely unrelated from the fact that it is a "default lib". The issue arrises from doing this:
```hxml
-lib heaps
-lib heaps:1.8.0
```
This is because in the entry in the map for the first one is "heaps", but for the second one it's "heaps:1.8.0", so they don't get treated as the same library as they should.

**Comment by tobil4sk** [comment] 2021-11-14 20:12
#530 fixes this, and includes a test.

**Comment by tobil4sk** [comment] 2021-11-14 21:03
Apologies, I misunderstood the problem because I couldn't reproduce it (the -cpp flag has to be in a separate hxml). Here's the test for it: #532.

**Comment by tobil4sk** [comment] 2021-12-20 19:45
> I've pushed a fix, but it needs a test to close the issue.

Should be good to close now that the test is done, right?

**Closed** 2021-12-20 20:37 UTC
Labels: haxe-foundation-partner, test-needed
