### ISSUE TITLE
Incorrect version in submit report

### ISSUE THREAD

**Issue by profelis** [HaxeFoundation/haxelib#225] opened 2015-06-23 20:40 UTC
`haxelib submit` show incorrect version number
```
...\bezier.hx\src\main\haxe> haxelib submit haxe.zip
Password :
Sending data....
File #60305756 accepted : 43882 bytes written
Processing file....
Version 1.0.4-alpha (id#2806) added                         ----------< version 1.0.4-alpha ((

...\bezier.hx\src\main\haxe> haxelib update bezier
Downloading bezier-1,0,4.zip...
Download complete : 43882 bytes in 0.8s (52.3KB/s)
  Created bezier/
  Install bezier/Bezier.hx
  Install bezier/Intersection.hx
  Install bezier/IParametric.hx
  Install bezier/Line.hx
  Created bezier/math/
  Install bezier/math/Equations.hx
  Created deep/
  Created deep/math/
  Install deep/math/Const.hx
  Install deep/math/Point.hx
  Install deep/math/Rect.hx
  Install haxelib.json
  Current version is now 1.0.4                                --------------< correct version
Done
```

**Comment by nadako** [comment] 2015-12-10 00:18
duplicate of #243

**Closed by nadako** 2015-12-10 00:18 UTC
