### ISSUE TITLE
Feature request: install from *.hxml file allows option to install automatically (without prompt).

### ISSUE THREAD

**Issue by dionjwa** [HaxeFoundation/haxelib#166] opened 2015-02-05 18:04 UTC
When installing haxe libraries as part of a build process, forcing the user to interact to confirm installation prevents this step being automatized.  

So add an option e.g. "--yes" that automatically answers yes to the install prompt.

**Comment by back2dos** [comment] 2015-03-12 14:53
I'm going to treat this as a duplicate of #167.

**Closed by back2dos** 2015-03-12 14:53 UTC
